@startuml
title: "add CCRD"
actor USER as "User"
participant APP as "TNGD APP"
participant mPASS as "mPass"

autonumber

USER -> APP :enter wallet duitnow landing page
APP -> mPASS : "request: {ap.tngdwallet.contact.favorite.list}"
APP <-- mPASS : "response: {data}"
alt serviceType=="PTA"
USER <-- APP : "mapping bankcode with native or AMCS bank data   \n then show real bankname on page list"
end

USER -> APP : "click a item enter transfer flow"

APP -> mPASS : "request: {ap.tngdwallet.duitnow.transfer}"\n {payeeFinInstName = real bankName}
APP <-- mPASS : "response: {data}
USER <-- APP : "show  real bankname  result page"


USER -> APP : "click add favourite button"

APP -> mPASS : "request: {ap.tngdwallet.contact.favorite.add}\n {bankname=real bankname}"
APP <-- mPASS : "response"
alt [success]
USER <-- APP : show added toast
end

USER ->APP: "visit history page"
APP -> mPASS : "request: {com.tngd.txn.wallet.detail}"
APP <-- mPASS : "response real bankname"
USER <-- APP : "show  real bankname  in history page page"


@enduml