@startuml
title: "add CCRD"
actor USER as "User"
participant LAND as "landing page"
participant RESULT as "Result page"
participant mPASS as "mPass"

autonumber

USER -> LAND :enter wallet transfer page
LAND -> mPASS : "request: {ap.tngdwallet.contact.favorite.list}"
LAND <-- mPASS : "response:{bankAccountNo ,encryptedBankAccountNo}"
USER <-- LAND : "show bankAccountNo"

USER -> LAND : "click a item"
group #lightblue [NEW flow]
alt  duitnow_ccrd_add_switch==true &&serviceType=="PTA" && transferType=="CCRD"
LAND -> mPASS : "request: {ap.tngdwallet.duitnow.account.decrypt.query}"\n {bankAccountNoEncrypted}
LAND <-- mPASS : "response: {decrypted bankAccountNo}
end
alt failed
USER <-- mPASS : show common error dialog
USER x<-- mPASS : return
end
end
LAND -> mPASS : "request: {ap.tngdwallet.duitnow.proxy.enquiry}"\n {receiverAccountNo = decrypted bankAccountNo}
LAND <-- mPASS : "response: {previous flow data}
USER <-- RESULT : "show full CCRD string in result page"

group #lightblue [NEW flow\n]
 alt  duitnow_ccrd_add_switch==false &&serviceType=="PTA" && transferType=="CCRD"
 USER <-- mPASS :  hide "add to favourite" button
 USER x<-- mPASS : return
 end
end

USER -> RESULT : "click add favourite button"

RESULT -> mPASS : "request: {ap.tngdwallet.contact.favorite.add}"
RESULT <-- mPASS : "response"
alt [success]
USER <-- RESULT : show added toast
end


@enduml