@startuml
title: "add CCRD"
actor USER as "User"
participant LAND as "landing page"
participant RESULT as "Result page"
participant mPASS as "mPass"

autonumber

USER -> LAND :enter wallet transfer page
LAND -> mPASS : "request: {ap.tngdwallet.contact.favorite.list}"
LAND <-- mPASS : "response:{bankAccountNo ,encryptedBankAccountNo}"
USER <-- LAND : "show bankAccountNo"

USER -> LAND : "click a item"
group #lightblue [NEW flow]
alt  serviceType=="PTA" && transferType=="CCRD"
LAND -> mPASS : "request: {ap.tngdwallet.duitnow.account.decrypt.query}"\n {bankAccountNoEncrypted}
LAND <-- mPASS : "response: {decrypted bankAccountNo}
end
alt failed
USER <-- mPASS : show error dialog "comfirm"
USER x<-- mPASS
end
end
LAND -> mPASS : "request: {ap.tngdwallet.duitnow.proxy.enquiry}"\n {receiverAccountNo = decrypted bankAccountNo}
LAND <-- mPASS : "response: {previous flow data}
USER <-- RESULT : "show full CCRD string in result page"
USER -> RESULT : "click add favourite button"

RESULT -> mPASS : "request: {ap.tngdwallet.contact.favorite.add}"
RESULT <-- mPASS : "response"
alt [success]
USER <-- RESULT : show added toast
end


@enduml