@startuml
'https://plantuml.com/activity-diagram-beta

start
: click reload;
: query duitNow accountId;
    note right
         ap.tngdwallet.external.accountid.query
         ====
         to get external account id from custcenter
    end note
if(is success) then (ture)
    :show account number;
else(false)
    :show gray frame;
        note right
        for duitNow account num ,Learn More button
        end note
stop
endif
: click Learn More;
: Page Duitnow Transfer;
: click Share DuitNow Account;
: show share drawer;

stop

@enduml
