package com.comm.util.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.comm.util.green.Message;
import com.comm.util.green.Device;
import com.comm.util.green.DeviceValueBean;
import com.comm.util.bean.Patient;

import com.comm.util.dao.MessageDao;
import com.comm.util.dao.DeviceDao;
import com.comm.util.dao.DeviceValueBeanDao;
import com.comm.util.dao.PatientDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageDaoConfig;
    private final DaoConfig deviceDaoConfig;
    private final DaoConfig deviceValueBeanDaoConfig;
    private final DaoConfig patientDaoConfig;

    private final MessageDao messageDao;
    private final DeviceDao deviceDao;
    private final DeviceValueBeanDao deviceValueBeanDao;
    private final PatientDao patientDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        deviceValueBeanDaoConfig = daoConfigMap.get(DeviceValueBeanDao.class).clone();
        deviceValueBeanDaoConfig.initIdentityScope(type);

        patientDaoConfig = daoConfigMap.get(PatientDao.class).clone();
        patientDaoConfig.initIdentityScope(type);

        messageDao = new MessageDao(messageDaoConfig, this);
        deviceDao = new DeviceDao(deviceDaoConfig, this);
        deviceValueBeanDao = new DeviceValueBeanDao(deviceValueBeanDaoConfig, this);
        patientDao = new PatientDao(patientDaoConfig, this);

        registerDao(Message.class, messageDao);
        registerDao(Device.class, deviceDao);
        registerDao(DeviceValueBean.class, deviceValueBeanDao);
        registerDao(Patient.class, patientDao);
    }
    
    public void clear() {
        messageDaoConfig.clearIdentityScope();
        deviceDaoConfig.clearIdentityScope();
        deviceValueBeanDaoConfig.clearIdentityScope();
        patientDaoConfig.clearIdentityScope();
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

    public DeviceValueBeanDao getDeviceValueBeanDao() {
        return deviceValueBeanDao;
    }

    public PatientDao getPatientDao() {
        return patientDao;
    }

}
