@startuml
'https://plantuml.com/sequence-diagram


actor USER as "User"
participant AMerchant as "A+ merchant/ACQP"
participant ASDK as "A+ Sdk"
participant backend as "Tngd Backend"
participant App as "App"
autonumber
 AMerchant -> ASDK : pay
 ASDK -> backend : pay
 AMerchant <-- backend : user balance not enough
 alt #lightyellow user not install "Tngd App"
 AMerchant ->x AMerchant: don't need resolve
 end
 AMerchant -> AMerchant : pop up error message and top up button
 USER -> AMerchant : Click top up button
 AMerchant -> ASDK : open  "Tngd App"(GolGoogleTopUpActivity)
 ASDK -> App : topUp Spi
 alt #lightyellow topup_googleplay_switch = false
 App ->x App : not resolved
 end
 alt #lightyellow  user not  login
 USER <-- App : open LoginPage with DeepLink \n [tngdwallet://client/dl/reload?source=google_topup_guide] \n flag = google_topup_entry
 USER <-- App: after login  get  deeplink   jump into Reload page
 end

 alt #lightyellow  user   logined
 USER <-- App: deeplink   jump into Reload page flag = google_topup_entry
 end
 USER -> App : reload operation

 alt #lightyellow succuss && extra_intent_flag == INTENT_FLAG_GOOGLE_PLAY_TOPUP
 USER <-- App :  show reload succuss page
 ASDK <-- App :  send event callback  [onSuccess(succuss)]
 else pending && extra_intent_flag == INTENT_FLAG_GOOGLE_PLAY_TOPUP
  USER <-- App : show pending page
  ASDK <-- App : send event callback [onFailure(FAILED)]
 else failed && extra_intent_flag == INTENT_FLAG_GOOGLE_PLAY_TOPUP
  USER <-- App : show failed page
  ASDK <-- App : send event callback sendcallback [onFailure(FAILED)]
  else RiskReject && extra_intent_flag == INTENT_FLAG_GOOGLE_PLAY_TOPUP
  USER <-- App : Rj failed page
  ASDK <-- App : send event callback sendcallback [onFailure(FAILED)]
 end
 USER -> App : User close reload Home page or page destroyed
 alt #lightyellow  extra_intent_flag == INTENT_FLAG_GOOGLE_PLAY_TOPUP
 ASDK <-- App : clickback eventbus sendcallback [onFailure(ABANDON)]
 end




@enduml