@startuml
'https://plantuml.com/activity-diagram-beta

start
if (version>=13?) then (yes)
  :request permission;
  if (granted?) is (yes) then
    if (channels is enable?) is (yes) then
      : next flow;
    else (no)
      :open channel page;
    endif
  else (no)
      if (notification switch?) is (yes) then
          if (channel switch?) is (yes) then
            : next flow;
          else (no)
          :open channel page;
          endif
       else (no)
        :open notification setting page;
       endif
  endif

else if(version>=8 && version<13?))is (yes) then
   if (notification switch?) is (yes) then
      if (channel switch?) is (yes) then
      : next flow;
      else (no)
      :open channel page;
      endif
   else (no)
    :open notification setting page;
   endif

else if(version<8?)is (yes) then
    if (notification switch?) is (yes) then
      : next flow;
     else (no)
      :open notification setting page;
     endif
endif

stop

@enduml
