@startuml
'https://plantuml.com/sequence-diagram

autonumber

Alice -> Bob: hello

note left: this is a firs note

Bob --> Alice: Authentication Response

'右边添加注释
Alice -> Bob: ok
note right: this is another note
Alice <-- Bob: I am thinking

' 添加长注释
note left
a note
can also be defined
an several lines
end note
@enduml